import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import { Zap, Loader2, Plus, Trash2, Calendar, Target, Eye, ArrowRight, ChevronDown, ChevronUp, Copy } from "lucide-react";
import axios from "axios";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

const PLATFORM_OPTIONS = [
  { id: "facebook", label: "Facebook" },
  { id: "instagram", label: "Instagram" },
  { id: "linkedin", label: "LinkedIn" },
  { id: "x", label: "X / Twitter" },
  { id: "tiktok", label: "TikTok" },
];

export default function CampaignManager() {
  const navigate = useNavigate();
  const token = localStorage.getItem("icf_token");
  const [campaigns, setCampaigns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [generating, setGenerating] = useState(null);
  const [showCreate, setShowCreate] = useState(false);
  const [expandedCampaign, setExpandedCampaign] = useState(null);
  const [form, setForm] = useState({
    name: "", goal: "leads", platforms: ["facebook", "instagram"],
    target_audience: "", duration_days: 30, description: ""
  });

  useEffect(() => {
    if (!token) { navigate("/auth"); return; }
    fetchCampaigns();
  }, [token, navigate]);

  const fetchCampaigns = async () => {
    try {
      const { data } = await axios.get(`${API}/campaigns`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setCampaigns(data);
    } catch {} finally { setLoading(false); }
  };

  const createCampaign = async (e) => {
    e.preventDefault();
    if (!form.name || !form.target_audience || form.platforms.length === 0) {
      toast.error("Fill in campaign name, target audience, and select platforms");
      return;
    }
    setCreating(true);
    try {
      const { data } = await axios.post(`${API}/campaigns`, form, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setCampaigns(prev => [data, ...prev]);
      setShowCreate(false);
      setForm({ name: "", goal: "leads", platforms: ["facebook", "instagram"], target_audience: "", duration_days: 30, description: "" });
      toast.success("Campaign created! Now generate AI content for it.");
    } catch (err) {
      toast.error(err.response?.data?.detail || "Failed to create campaign");
    } finally { setCreating(false); }
  };

  const generateContent = async (campaignId) => {
    setGenerating(campaignId);
    try {
      const { data } = await axios.post(`${API}/campaigns/${campaignId}/generate`, {}, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setCampaigns(prev => prev.map(c => c.id === campaignId ? data : c));
      setExpandedCampaign(campaignId);
      toast.success("Campaign content generated by AI!");
    } catch (err) {
      toast.error(err.response?.data?.detail || "Generation failed");
    } finally { setGenerating(null); }
  };

  const deleteCampaign = async (id) => {
    try {
      await axios.delete(`${API}/campaigns/${id}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      setCampaigns(prev => prev.filter(c => c.id !== id));
      toast.success("Campaign deleted");
    } catch { toast.error("Failed to delete"); }
  };

  const togglePlatform = (platformId) => {
    setForm(prev => ({
      ...prev,
      platforms: prev.platforms.includes(platformId)
        ? prev.platforms.filter(p => p !== platformId)
        : [...prev.platforms, platformId]
    }));
  };

  const copyPost = (text) => {
    navigator.clipboard.writeText(text);
    toast.success("Post copied!");
  };

  const goalLabels = { awareness: "Brand Awareness", leads: "Lead Generation", engagement: "Engagement", traffic: "Website Traffic" };
  const statusColors = { draft: "bg-gray-100 text-gray-600", generated: "bg-green-100 text-green-700", active: "bg-blue-100 text-blue-700", completed: "bg-purple-100 text-purple-700" };

  if (loading) return <div className="pt-16 min-h-screen flex items-center justify-center"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>;

  return (
    <div className="pt-16 min-h-screen bg-background">
      <div className="max-w-7xl mx-auto px-6 lg:px-8 py-8">
        <div className="flex items-center justify-between mb-8">
          <div>
            <span className="mono-label mb-1 block">AI AGENT</span>
            <h1 className="text-2xl sm:text-3xl font-bold" style={{ fontFamily: "'Clash Display', sans-serif" }}>
              Campaign <span className="text-primary">Manager</span>
            </h1>
            <p className="text-sm text-muted-foreground mt-1">AI creates and manages multi-platform marketing campaigns</p>
          </div>
          <Button
            data-testid="campaign-create-toggle-btn"
            onClick={() => setShowCreate(!showCreate)}
            className="rounded-sm text-xs tracking-widest font-bold uppercase hard-shadow"
          >
            <Plus className="w-4 h-4 mr-2" /> NEW CAMPAIGN
          </Button>
        </div>

        {/* Create Campaign Form */}
        {showCreate && (
          <form onSubmit={createCampaign} data-testid="campaign-create-form" className="bg-card border border-border rounded-sm p-6 mb-8 relative tech-corner">
            <h3 className="text-sm font-bold tracking-widest uppercase mb-6" style={{ fontFamily: "'Clash Display', sans-serif" }}>
              Create New Campaign
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label className="mono-label mb-2 block">CAMPAIGN NAME *</Label>
                <Input
                  data-testid="campaign-name-input"
                  value={form.name}
                  onChange={e => setForm(p => ({ ...p, name: e.target.value }))}
                  placeholder="e.g., Spring ICF Home Campaign"
                  className="rounded-sm bg-muted/50"
                />
              </div>
              <div>
                <Label className="mono-label mb-2 block">GOAL</Label>
                <Select value={form.goal} onValueChange={v => setForm(p => ({ ...p, goal: v }))}>
                  <SelectTrigger data-testid="campaign-goal-select" className="rounded-sm bg-muted/50"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="leads">Lead Generation</SelectItem>
                    <SelectItem value="awareness">Brand Awareness</SelectItem>
                    <SelectItem value="engagement">Engagement</SelectItem>
                    <SelectItem value="traffic">Website Traffic</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="mono-label mb-2 block">TARGET AUDIENCE *</Label>
                <Input
                  data-testid="campaign-audience-input"
                  value={form.target_audience}
                  onChange={e => setForm(p => ({ ...p, target_audience: e.target.value }))}
                  placeholder="e.g., Homeowners in Texas planning new builds"
                  className="rounded-sm bg-muted/50"
                />
              </div>
              <div>
                <Label className="mono-label mb-2 block">DURATION (DAYS)</Label>
                <Input
                  data-testid="campaign-duration-input"
                  type="number"
                  value={form.duration_days}
                  onChange={e => setForm(p => ({ ...p, duration_days: parseInt(e.target.value) || 30 }))}
                  className="rounded-sm bg-muted/50"
                />
              </div>
              <div className="md:col-span-2">
                <Label className="mono-label mb-2 block">PLATFORMS *</Label>
                <div className="flex flex-wrap gap-4">
                  {PLATFORM_OPTIONS.map(p => (
                    <label key={p.id} className="flex items-center gap-2 cursor-pointer">
                      <Checkbox
                        data-testid={`campaign-platform-${p.id}`}
                        checked={form.platforms.includes(p.id)}
                        onCheckedChange={() => togglePlatform(p.id)}
                      />
                      <span className="text-sm">{p.label}</span>
                    </label>
                  ))}
                </div>
              </div>
              <div className="md:col-span-2">
                <Label className="mono-label mb-2 block">ADDITIONAL DETAILS</Label>
                <Textarea
                  data-testid="campaign-description-input"
                  value={form.description}
                  onChange={e => setForm(p => ({ ...p, description: e.target.value }))}
                  placeholder="Any specific themes, promotions, seasonal tie-ins..."
                  rows={3}
                  className="rounded-sm bg-muted/50"
                />
              </div>
            </div>
            <div className="flex gap-3 mt-6">
              <Button data-testid="campaign-submit-btn" type="submit" disabled={creating} className="rounded-sm text-xs tracking-widest font-bold uppercase hard-shadow">
                {creating && <Loader2 className="w-4 h-4 animate-spin mr-2" />}
                CREATE CAMPAIGN
              </Button>
              <Button type="button" variant="outline" onClick={() => setShowCreate(false)} className="rounded-sm text-xs tracking-widest uppercase">
                CANCEL
              </Button>
            </div>
          </form>
        )}

        {/* Campaigns List */}
        {campaigns.length === 0 ? (
          <div className="bg-card border border-dashed border-border rounded-sm p-16 text-center">
            <Zap className="w-10 h-10 text-muted-foreground/20 mx-auto mb-4" />
            <h3 className="text-lg font-bold mb-2" style={{ fontFamily: "'Clash Display', sans-serif" }}>No Campaigns Yet</h3>
            <p className="text-sm text-muted-foreground mb-4">Create your first AI-powered marketing campaign.</p>
            <Button onClick={() => setShowCreate(true)} className="rounded-sm text-xs tracking-widest font-bold uppercase">
              <Plus className="w-4 h-4 mr-2" /> CREATE CAMPAIGN
            </Button>
          </div>
        ) : (
          <div className="space-y-4">
            {campaigns.map((campaign, idx) => (
              <div key={campaign.id} data-testid={`campaign-card-${idx}`} className="bg-card border border-border rounded-sm overflow-hidden">
                <div className="p-6">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="text-base font-bold" style={{ fontFamily: "'Clash Display', sans-serif" }}>{campaign.name}</h3>
                        <Badge className={`text-[10px] tracking-wider uppercase rounded-sm border ${statusColors[campaign.status] || "bg-gray-100 text-gray-600"}`}>
                          {campaign.status}
                        </Badge>
                      </div>
                      <div className="flex flex-wrap gap-3 text-xs text-muted-foreground mb-2">
                        <span className="flex items-center gap-1"><Target className="w-3 h-3" />{goalLabels[campaign.goal] || campaign.goal}</span>
                        <span className="flex items-center gap-1"><Calendar className="w-3 h-3" />{campaign.duration_days} days</span>
                        <span className="flex items-center gap-1"><Eye className="w-3 h-3" />{campaign.target_audience}</span>
                      </div>
                      <div className="flex flex-wrap gap-1.5">
                        {campaign.platforms?.map(p => (
                          <Badge key={p} variant="secondary" className="text-[10px] tracking-wider uppercase rounded-sm">{p}</Badge>
                        ))}
                      </div>
                    </div>
                    <div className="flex items-center gap-2 ml-4">
                      {campaign.status === "draft" && (
                        <Button
                          data-testid={`campaign-generate-btn-${idx}`}
                          onClick={() => generateContent(campaign.id)}
                          disabled={generating === campaign.id}
                          size="sm"
                          className="rounded-sm text-xs tracking-widest font-bold uppercase"
                        >
                          {generating === campaign.id ? <Loader2 className="w-3 h-3 animate-spin mr-1" /> : <Zap className="w-3 h-3 mr-1" />}
                          GENERATE
                        </Button>
                      )}
                      {campaign.ai_content && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setExpandedCampaign(expandedCampaign === campaign.id ? null : campaign.id)}
                          className="rounded-sm text-xs tracking-widest uppercase"
                        >
                          {expandedCampaign === campaign.id ? <ChevronUp className="w-3 h-3 mr-1" /> : <ChevronDown className="w-3 h-3 mr-1" />}
                          CONTENT
                        </Button>
                      )}
                      <button onClick={() => deleteCampaign(campaign.id)} className="p-2 hover:bg-muted rounded-sm">
                        <Trash2 className="w-4 h-4 text-muted-foreground" />
                      </button>
                    </div>
                  </div>
                </div>

                {/* Expanded Campaign Content */}
                {expandedCampaign === campaign.id && campaign.ai_content && (
                  <div className="border-t border-border p-6 bg-muted/20">
                    {campaign.ai_content.strategy && (
                      <div className="mb-6 p-4 bg-card border border-dashed border-border rounded-sm">
                        <span className="mono-label block mb-2">CAMPAIGN STRATEGY</span>
                        <p className="text-sm text-foreground/80 leading-relaxed">{campaign.ai_content.strategy}</p>
                      </div>
                    )}

                    {campaign.ai_content.seo_keywords?.length > 0 && (
                      <div className="mb-6">
                        <span className="mono-label block mb-2">SEO KEYWORDS</span>
                        <div className="flex flex-wrap gap-1.5">
                          {campaign.ai_content.seo_keywords.map((kw, i) => (
                            <Badge key={i} variant="outline" className="text-[10px] rounded-sm">{kw}</Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {campaign.ai_content.content_calendar?.length > 0 && (
                      <div>
                        <span className="mono-label block mb-3">CONTENT CALENDAR ({campaign.ai_content.content_calendar.length} POSTS)</span>
                        <div className="space-y-3">
                          {campaign.ai_content.content_calendar.map((post, i) => (
                            <div key={i} data-testid={`campaign-post-${idx}-${i}`} className="bg-card border border-border rounded-sm p-4 group">
                              <div className="flex items-center justify-between mb-2">
                                <div className="flex items-center gap-2">
                                  <Badge variant="secondary" className="text-[10px] rounded-sm uppercase">{post.platform}</Badge>
                                  <span className="mono-label text-[9px]">DAY {post.day}</span>
                                  {post.best_time && <span className="mono-label text-[9px]">{post.best_time}</span>}
                                  {post.content_type && <Badge variant="outline" className="text-[9px] rounded-sm">{post.content_type}</Badge>}
                                </div>
                                <button onClick={() => copyPost(post.post_text)} className="opacity-0 group-hover:opacity-100 transition-opacity p-1 hover:bg-muted rounded-sm">
                                  <Copy className="w-3 h-3 text-muted-foreground" />
                                </button>
                              </div>
                              <p className="text-sm leading-relaxed mb-2 whitespace-pre-wrap">{post.post_text}</p>
                              {post.hashtags?.length > 0 && (
                                <div className="flex flex-wrap gap-1">
                                  {post.hashtags.map((tag, j) => (
                                    <span key={j} className="text-[10px] text-primary">{tag.startsWith("#") ? tag : `#${tag}`}</span>
                                  ))}
                                </div>
                              )}
                              {post.cta && <p className="text-xs text-primary font-semibold mt-1">CTA: {post.cta}</p>}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {campaign.ai_content.target_metrics && (
                      <div className="mt-6 p-4 bg-card border border-dashed border-border rounded-sm">
                        <span className="mono-label block mb-2">PROJECTED METRICS</span>
                        <div className="grid grid-cols-2 gap-4">
                          {Object.entries(campaign.ai_content.target_metrics).map(([key, val]) => (
                            <div key={key}>
                              <span className="mono-label text-[9px] block">{key.toUpperCase()}</span>
                              <span className="text-sm font-semibold">{val}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
